---
- name: Update package index
  yum:
    name: '*'
    state: latest
  become: true

- name: Install Docker
  yum:
    name: docker
    state: present
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: true


