---
- name: Update package index and install dependencies
  apt:
    update_cache: yes
    name: apt-transport-https, ca-certificates, curl, software-properties-common
  become: true

- name: Get GPG key (Ubuntu)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker
  become: true

- name: Update package index and install Docker
  apt:
    update_cache: yes
    name: docker-ce, docker-ce-cli, containerd.io
  become: true

- name: Verify Docker is running
  service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Install Docker Python library
  ansible.builtin.pip:
    name: docker
    version: 5.0.0
    state: present

- name: Install Docker-Compose Python library
  ansible.builtin.pip:
    name: docker-compose
    version: 1.29.2
    state: present
