version: "3"
services:
  apache:
    build: ./apache-meister
    ports:
      - "8080:8080"
    networks:
      - web

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web

networks:
  web: